# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3f17e9158270a33b558bcc4db0c62a2fea8ff0c1d76c6907b7b7775d8129994234c44ceb3e9a8810831e2ae167ee9cbb490bee063e51315733a6b89fd06d5b7

test:
  secret_key_base: f80605e631102d7693a81a0db3a4e0193eec58ae25be046860190cf46c726ca90c021fba26b90281648bacf17d4398afd15d68d36dcb87b24c732c80c0a919e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
